// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: eightball/eightball/current_magic_key.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CurrentMagicKey struct {
	CurrentMagicKey uint64 `protobuf:"varint,1,opt,name=currentMagicKey,proto3" json:"currentMagicKey,omitempty"`
	SinceBlock      uint64 `protobuf:"varint,2,opt,name=sinceBlock,proto3" json:"sinceBlock,omitempty"`
}

func (m *CurrentMagicKey) Reset()         { *m = CurrentMagicKey{} }
func (m *CurrentMagicKey) String() string { return proto.CompactTextString(m) }
func (*CurrentMagicKey) ProtoMessage()    {}
func (*CurrentMagicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb528aeb1cfa38b8, []int{0}
}
func (m *CurrentMagicKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CurrentMagicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CurrentMagicKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CurrentMagicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentMagicKey.Merge(m, src)
}
func (m *CurrentMagicKey) XXX_Size() int {
	return m.Size()
}
func (m *CurrentMagicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentMagicKey.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentMagicKey proto.InternalMessageInfo

func (m *CurrentMagicKey) GetCurrentMagicKey() uint64 {
	if m != nil {
		return m.CurrentMagicKey
	}
	return 0
}

func (m *CurrentMagicKey) GetSinceBlock() uint64 {
	if m != nil {
		return m.SinceBlock
	}
	return 0
}

func init() {
	proto.RegisterType((*CurrentMagicKey)(nil), "eightball.eightball.CurrentMagicKey")
}

func init() {
	proto.RegisterFile("eightball/eightball/current_magic_key.proto", fileDescriptor_fb528aeb1cfa38b8)
}

var fileDescriptor_fb528aeb1cfa38b8 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4e, 0xcd, 0x4c, 0xcf,
	0x28, 0x49, 0x4a, 0xcc, 0xc9, 0xd1, 0x47, 0xb0, 0x92, 0x4b, 0x8b, 0x8a, 0x52, 0xf3, 0x4a, 0xe2,
	0x73, 0x13, 0xd3, 0x33, 0x93, 0xe3, 0xb3, 0x53, 0x2b, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85,
	0x84, 0xe1, 0x4a, 0xf4, 0xe0, 0x2c, 0xa5, 0x68, 0x2e, 0x7e, 0x67, 0x88, 0x7a, 0x5f, 0x90, 0x72,
	0xef, 0xd4, 0x4a, 0x21, 0x0d, 0x2e, 0xfe, 0x64, 0x54, 0x21, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x96,
	0x20, 0x74, 0x61, 0x21, 0x39, 0x2e, 0xae, 0xe2, 0xcc, 0xbc, 0xe4, 0x54, 0xa7, 0x9c, 0xfc, 0xe4,
	0x6c, 0x09, 0x26, 0xb0, 0x22, 0x24, 0x11, 0x27, 0xd3, 0x13, 0x8f, 0xe4, 0x18, 0x2f, 0x3c, 0x92,
	0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc2, 0x63, 0x39, 0x86, 0x0b, 0x8f, 0xe5, 0x18, 0x6e, 0x3c,
	0x96, 0x63, 0x88, 0x92, 0x46, 0x38, 0xb7, 0x02, 0xc9, 0xe9, 0x25, 0x95, 0x05, 0xa9, 0xc5, 0x49,
	0x6c, 0x60, 0xf7, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x78, 0x8a, 0x22, 0x80, 0xde, 0x00,
	0x00, 0x00,
}

func (m *CurrentMagicKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CurrentMagicKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CurrentMagicKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SinceBlock != 0 {
		i = encodeVarintCurrentMagicKey(dAtA, i, uint64(m.SinceBlock))
		i--
		dAtA[i] = 0x10
	}
	if m.CurrentMagicKey != 0 {
		i = encodeVarintCurrentMagicKey(dAtA, i, uint64(m.CurrentMagicKey))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCurrentMagicKey(dAtA []byte, offset int, v uint64) int {
	offset -= sovCurrentMagicKey(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CurrentMagicKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CurrentMagicKey != 0 {
		n += 1 + sovCurrentMagicKey(uint64(m.CurrentMagicKey))
	}
	if m.SinceBlock != 0 {
		n += 1 + sovCurrentMagicKey(uint64(m.SinceBlock))
	}
	return n
}

func sovCurrentMagicKey(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCurrentMagicKey(x uint64) (n int) {
	return sovCurrentMagicKey(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CurrentMagicKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCurrentMagicKey
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CurrentMagicKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CurrentMagicKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentMagicKey", wireType)
			}
			m.CurrentMagicKey = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurrentMagicKey
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentMagicKey |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SinceBlock", wireType)
			}
			m.SinceBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurrentMagicKey
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SinceBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCurrentMagicKey(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCurrentMagicKey
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCurrentMagicKey(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCurrentMagicKey
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCurrentMagicKey
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCurrentMagicKey
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCurrentMagicKey
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCurrentMagicKey
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCurrentMagicKey
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCurrentMagicKey        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCurrentMagicKey          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCurrentMagicKey = fmt.Errorf("proto: unexpected end of group")
)
