// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: eightball/eightball/high_council.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HighCouncil struct {
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MagicKeyId    uint64 `protobuf:"varint,2,opt,name=magicKeyId,proto3" json:"magicKeyId,omitempty"`
	SpiritAddress string `protobuf:"bytes,3,opt,name=spiritAddress,proto3" json:"spiritAddress,omitempty"`
	SpiritPubKey  string `protobuf:"bytes,4,opt,name=spiritPubKey,proto3" json:"spiritPubKey,omitempty"`
}

func (m *HighCouncil) Reset()         { *m = HighCouncil{} }
func (m *HighCouncil) String() string { return proto.CompactTextString(m) }
func (*HighCouncil) ProtoMessage()    {}
func (*HighCouncil) Descriptor() ([]byte, []int) {
	return fileDescriptor_c99fe84f94cba129, []int{0}
}
func (m *HighCouncil) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HighCouncil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HighCouncil.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HighCouncil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HighCouncil.Merge(m, src)
}
func (m *HighCouncil) XXX_Size() int {
	return m.Size()
}
func (m *HighCouncil) XXX_DiscardUnknown() {
	xxx_messageInfo_HighCouncil.DiscardUnknown(m)
}

var xxx_messageInfo_HighCouncil proto.InternalMessageInfo

func (m *HighCouncil) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HighCouncil) GetMagicKeyId() uint64 {
	if m != nil {
		return m.MagicKeyId
	}
	return 0
}

func (m *HighCouncil) GetSpiritAddress() string {
	if m != nil {
		return m.SpiritAddress
	}
	return ""
}

func (m *HighCouncil) GetSpiritPubKey() string {
	if m != nil {
		return m.SpiritPubKey
	}
	return ""
}

func init() {
	proto.RegisterType((*HighCouncil)(nil), "eightball.eightball.HighCouncil")
}

func init() {
	proto.RegisterFile("eightball/eightball/high_council.proto", fileDescriptor_c99fe84f94cba129)
}

var fileDescriptor_c99fe84f94cba129 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4b, 0xcd, 0x4c, 0xcf,
	0x28, 0x49, 0x4a, 0xcc, 0xc9, 0xd1, 0x47, 0xb0, 0x32, 0x32, 0xd3, 0x33, 0xe2, 0x93, 0xf3, 0x4b,
	0xf3, 0x92, 0x33, 0x73, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x84, 0xe1, 0xb2, 0x7a, 0x70,
	0x96, 0x52, 0x3b, 0x23, 0x17, 0xb7, 0x47, 0x66, 0x7a, 0x86, 0x33, 0x44, 0xa9, 0x10, 0x1f, 0x17,
	0x53, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4b, 0x10, 0x53, 0x66, 0x8a, 0x90, 0x1c, 0x17,
	0x57, 0x6e, 0x62, 0x7a, 0x66, 0xb2, 0x77, 0x6a, 0xa5, 0x67, 0x8a, 0x04, 0x13, 0x58, 0x1c, 0x49,
	0x44, 0x48, 0x85, 0x8b, 0xb7, 0xb8, 0x20, 0xb3, 0x28, 0xb3, 0xc4, 0x31, 0x25, 0xa5, 0x28, 0xb5,
	0xb8, 0x58, 0x82, 0x59, 0x81, 0x51, 0x83, 0x33, 0x08, 0x55, 0x50, 0x48, 0x89, 0x8b, 0x07, 0x22,
	0x10, 0x50, 0x9a, 0xe4, 0x9d, 0x5a, 0x29, 0xc1, 0x02, 0x56, 0x84, 0x22, 0xe6, 0x64, 0x7a, 0xe2,
	0x91, 0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0x4e, 0x78, 0x2c, 0xc7, 0x70,
	0xe1, 0xb1, 0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x51, 0xd2, 0x08, 0x6f, 0x55, 0x20, 0x79, 0xb1,
	0xa4, 0xb2, 0x20, 0xb5, 0x38, 0x89, 0x0d, 0xec, 0x39, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x28, 0x85, 0x67, 0x7e, 0x06, 0x01, 0x00, 0x00,
}

func (m *HighCouncil) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HighCouncil) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HighCouncil) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SpiritPubKey) > 0 {
		i -= len(m.SpiritPubKey)
		copy(dAtA[i:], m.SpiritPubKey)
		i = encodeVarintHighCouncil(dAtA, i, uint64(len(m.SpiritPubKey)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SpiritAddress) > 0 {
		i -= len(m.SpiritAddress)
		copy(dAtA[i:], m.SpiritAddress)
		i = encodeVarintHighCouncil(dAtA, i, uint64(len(m.SpiritAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if m.MagicKeyId != 0 {
		i = encodeVarintHighCouncil(dAtA, i, uint64(m.MagicKeyId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintHighCouncil(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintHighCouncil(dAtA []byte, offset int, v uint64) int {
	offset -= sovHighCouncil(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HighCouncil) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovHighCouncil(uint64(m.Id))
	}
	if m.MagicKeyId != 0 {
		n += 1 + sovHighCouncil(uint64(m.MagicKeyId))
	}
	l = len(m.SpiritAddress)
	if l > 0 {
		n += 1 + l + sovHighCouncil(uint64(l))
	}
	l = len(m.SpiritPubKey)
	if l > 0 {
		n += 1 + l + sovHighCouncil(uint64(l))
	}
	return n
}

func sovHighCouncil(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHighCouncil(x uint64) (n int) {
	return sovHighCouncil(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HighCouncil) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHighCouncil
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HighCouncil: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HighCouncil: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHighCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MagicKeyId", wireType)
			}
			m.MagicKeyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHighCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MagicKeyId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpiritAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHighCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHighCouncil
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHighCouncil
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpiritAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpiritPubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHighCouncil
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHighCouncil
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHighCouncil
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpiritPubKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHighCouncil(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHighCouncil
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHighCouncil(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHighCouncil
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHighCouncil
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHighCouncil
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHighCouncil
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHighCouncil
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHighCouncil
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHighCouncil        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHighCouncil          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHighCouncil = fmt.Errorf("proto: unexpected end of group")
)
