// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: eightball/eightball/kill_meditation_summoning.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type KillMeditationSummoning struct {
	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Height   uint64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Metadata string `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Creator  string `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *KillMeditationSummoning) Reset()         { *m = KillMeditationSummoning{} }
func (m *KillMeditationSummoning) String() string { return proto.CompactTextString(m) }
func (*KillMeditationSummoning) ProtoMessage()    {}
func (*KillMeditationSummoning) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb983de23e3ac468, []int{0}
}
func (m *KillMeditationSummoning) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KillMeditationSummoning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KillMeditationSummoning.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KillMeditationSummoning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillMeditationSummoning.Merge(m, src)
}
func (m *KillMeditationSummoning) XXX_Size() int {
	return m.Size()
}
func (m *KillMeditationSummoning) XXX_DiscardUnknown() {
	xxx_messageInfo_KillMeditationSummoning.DiscardUnknown(m)
}

var xxx_messageInfo_KillMeditationSummoning proto.InternalMessageInfo

func (m *KillMeditationSummoning) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *KillMeditationSummoning) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *KillMeditationSummoning) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *KillMeditationSummoning) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*KillMeditationSummoning)(nil), "eightball.eightball.KillMeditationSummoning")
}

func init() {
	proto.RegisterFile("eightball/eightball/kill_meditation_summoning.proto", fileDescriptor_eb983de23e3ac468)
}

var fileDescriptor_eb983de23e3ac468 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4e, 0xcd, 0x4c, 0xcf,
	0x28, 0x49, 0x4a, 0xcc, 0xc9, 0xd1, 0x47, 0xb0, 0xb2, 0x33, 0x73, 0x72, 0xe2, 0x73, 0x53, 0x53,
	0x32, 0x4b, 0x12, 0x4b, 0x32, 0xf3, 0xf3, 0xe2, 0x8b, 0x4b, 0x73, 0x73, 0xf3, 0xf3, 0x32, 0xf3,
	0xd2, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x84, 0xe1, 0x4a, 0xf5, 0xe0, 0x2c, 0xa5, 0x72,
	0x2e, 0x71, 0xef, 0xcc, 0x9c, 0x1c, 0x5f, 0xb8, 0xb6, 0x60, 0x98, 0x2e, 0x21, 0x3e, 0x2e, 0xa6,
	0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x96, 0x20, 0xa6, 0xcc, 0x14, 0x21, 0x31, 0x2e, 0xb6,
	0x0c, 0xb0, 0x46, 0x09, 0x26, 0xb0, 0x18, 0x94, 0x27, 0x24, 0xc5, 0xc5, 0x91, 0x9b, 0x5a, 0x92,
	0x98, 0x92, 0x58, 0x92, 0x28, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe7, 0x0b, 0x49, 0x70,
	0xb1, 0x27, 0x17, 0xa5, 0x26, 0x96, 0xe4, 0x17, 0x49, 0xb0, 0x80, 0xa5, 0x60, 0x5c, 0x27, 0xd3,
	0x13, 0x8f, 0xe4, 0x18, 0x2f, 0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc2, 0x63, 0x39,
	0x86, 0x0b, 0x8f, 0xe5, 0x18, 0x6e, 0x3c, 0x96, 0x63, 0x88, 0x92, 0x46, 0x78, 0xa9, 0x02, 0xc9,
	0x7b, 0x25, 0x95, 0x05, 0xa9, 0xc5, 0x49, 0x6c, 0x60, 0xbf, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x5d, 0xdb, 0x2c, 0x99, 0x02, 0x01, 0x00, 0x00,
}

func (m *KillMeditationSummoning) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KillMeditationSummoning) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KillMeditationSummoning) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintKillMeditationSummoning(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Metadata) > 0 {
		i -= len(m.Metadata)
		copy(dAtA[i:], m.Metadata)
		i = encodeVarintKillMeditationSummoning(dAtA, i, uint64(len(m.Metadata)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Height != 0 {
		i = encodeVarintKillMeditationSummoning(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintKillMeditationSummoning(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintKillMeditationSummoning(dAtA []byte, offset int, v uint64) int {
	offset -= sovKillMeditationSummoning(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *KillMeditationSummoning) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovKillMeditationSummoning(uint64(m.Id))
	}
	if m.Height != 0 {
		n += 1 + sovKillMeditationSummoning(uint64(m.Height))
	}
	l = len(m.Metadata)
	if l > 0 {
		n += 1 + l + sovKillMeditationSummoning(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovKillMeditationSummoning(uint64(l))
	}
	return n
}

func sovKillMeditationSummoning(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozKillMeditationSummoning(x uint64) (n int) {
	return sovKillMeditationSummoning(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *KillMeditationSummoning) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowKillMeditationSummoning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KillMeditationSummoning: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KillMeditationSummoning: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKillMeditationSummoning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKillMeditationSummoning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKillMeditationSummoning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKillMeditationSummoning
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKillMeditationSummoning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metadata = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKillMeditationSummoning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKillMeditationSummoning
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKillMeditationSummoning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipKillMeditationSummoning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthKillMeditationSummoning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipKillMeditationSummoning(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowKillMeditationSummoning
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowKillMeditationSummoning
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowKillMeditationSummoning
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthKillMeditationSummoning
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupKillMeditationSummoning
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthKillMeditationSummoning
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthKillMeditationSummoning        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowKillMeditationSummoning          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupKillMeditationSummoning = fmt.Errorf("proto: unexpected end of group")
)
