// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: eightball/eightball/magic_key_summoning.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MagicKeySummoning struct {
	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MagicKeyId  uint64 `protobuf:"varint,2,opt,name=magicKeyId,proto3" json:"magicKeyId,omitempty"`
	BlockHeight uint64 `protobuf:"varint,3,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
}

func (m *MagicKeySummoning) Reset()         { *m = MagicKeySummoning{} }
func (m *MagicKeySummoning) String() string { return proto.CompactTextString(m) }
func (*MagicKeySummoning) ProtoMessage()    {}
func (*MagicKeySummoning) Descriptor() ([]byte, []int) {
	return fileDescriptor_0878bef3bbe94e3f, []int{0}
}
func (m *MagicKeySummoning) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MagicKeySummoning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MagicKeySummoning.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MagicKeySummoning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MagicKeySummoning.Merge(m, src)
}
func (m *MagicKeySummoning) XXX_Size() int {
	return m.Size()
}
func (m *MagicKeySummoning) XXX_DiscardUnknown() {
	xxx_messageInfo_MagicKeySummoning.DiscardUnknown(m)
}

var xxx_messageInfo_MagicKeySummoning proto.InternalMessageInfo

func (m *MagicKeySummoning) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MagicKeySummoning) GetMagicKeyId() uint64 {
	if m != nil {
		return m.MagicKeyId
	}
	return 0
}

func (m *MagicKeySummoning) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*MagicKeySummoning)(nil), "eightball.eightball.MagicKeySummoning")
}

func init() {
	proto.RegisterFile("eightball/eightball/magic_key_summoning.proto", fileDescriptor_0878bef3bbe94e3f)
}

var fileDescriptor_0878bef3bbe94e3f = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4d, 0xcd, 0x4c, 0xcf,
	0x28, 0x49, 0x4a, 0xcc, 0xc9, 0xd1, 0x47, 0xb0, 0x72, 0x13, 0xd3, 0x33, 0x93, 0xe3, 0xb3, 0x53,
	0x2b, 0xe3, 0x8b, 0x4b, 0x73, 0x73, 0xf3, 0xf3, 0x32, 0xf3, 0xd2, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b,
	0xf2, 0x85, 0x84, 0xe1, 0x8a, 0xf4, 0xe0, 0x2c, 0xa5, 0x54, 0x2e, 0x41, 0x5f, 0x90, 0x0e, 0xef,
	0xd4, 0xca, 0x60, 0x98, 0x7a, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0x96, 0x20, 0xa6, 0xcc, 0x14, 0x21, 0x39, 0x2e, 0xae, 0x5c, 0xa8, 0x22, 0xcf, 0x14, 0x09, 0x26,
	0xb0, 0x38, 0x92, 0x88, 0x90, 0x02, 0x17, 0x77, 0x52, 0x4e, 0x7e, 0x72, 0xb6, 0x07, 0xd8, 0x5c,
	0x09, 0x66, 0xb0, 0x02, 0x64, 0x21, 0x27, 0xd3, 0x13, 0x8f, 0xe4, 0x18, 0x2f, 0x3c, 0x92, 0x63,
	0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc2, 0x63, 0x39, 0x86, 0x0b, 0x8f, 0xe5, 0x18, 0x6e, 0x3c, 0x96,
	0x63, 0x88, 0x92, 0x46, 0x38, 0xbd, 0x02, 0xc9, 0x1b, 0x25, 0x95, 0x05, 0xa9, 0xc5, 0x49, 0x6c,
	0x60, 0x97, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xde, 0xd6, 0x5a, 0xea, 0x00, 0x00,
	0x00,
}

func (m *MagicKeySummoning) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MagicKeySummoning) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MagicKeySummoning) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintMagicKeySummoning(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.MagicKeyId != 0 {
		i = encodeVarintMagicKeySummoning(dAtA, i, uint64(m.MagicKeyId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintMagicKeySummoning(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMagicKeySummoning(dAtA []byte, offset int, v uint64) int {
	offset -= sovMagicKeySummoning(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MagicKeySummoning) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovMagicKeySummoning(uint64(m.Id))
	}
	if m.MagicKeyId != 0 {
		n += 1 + sovMagicKeySummoning(uint64(m.MagicKeyId))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovMagicKeySummoning(uint64(m.BlockHeight))
	}
	return n
}

func sovMagicKeySummoning(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMagicKeySummoning(x uint64) (n int) {
	return sovMagicKeySummoning(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MagicKeySummoning) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMagicKeySummoning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MagicKeySummoning: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MagicKeySummoning: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMagicKeySummoning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MagicKeyId", wireType)
			}
			m.MagicKeyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMagicKeySummoning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MagicKeyId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMagicKeySummoning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMagicKeySummoning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMagicKeySummoning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMagicKeySummoning(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMagicKeySummoning
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMagicKeySummoning
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMagicKeySummoning
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMagicKeySummoning
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMagicKeySummoning
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMagicKeySummoning
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMagicKeySummoning        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMagicKeySummoning          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMagicKeySummoning = fmt.Errorf("proto: unexpected end of group")
)
